<a href="https://colab.research.google.com/github/Barleysack/RawCodingDL/blob/main/Pre_Course_09_Pytorch_TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import torch as tch

In [4]:
#텐서 |t|는 배치사이즈와 차원을 곱한 값을 크기로 가진다. 
#파이토치는 첫번째 차원의 값이 세로값, 두번째 차원 값이 가로값, 세번째 차원 값이 깊이를 뜻한다. 
#하나의 관습. 기본적으로는 이러한 형태를 따른다. 
#NLP의 경우에도... 배치사이즈 * 길이* 디멘션


In [8]:
t=np.array(np.arange(10))

In [6]:
 print(t)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(t.ndim)
print(t.shape)

1
(10,)


In [10]:
print(t[0])

0


In [18]:
k= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(k)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
 a = torch.FloatTensor([0,2,3,4,5,5,6,6,7])
 print(a)

tensor([0., 2., 3., 4., 5., 5., 6., 6., 7.])


In [21]:
a.dim #뭐 np쪽이랑 비슷한거 다 잘 나오는 것을 알 수 있다. 

<function Tensor.dim>

In [32]:
a1 = torch.FloatTensor([[3,3]])
a2 = torch.FloatTensor([[2],[1]])
a1+a2

tensor([[5., 5.],
        [4., 4.]])

In [33]:
a1*a2
#Broadcasting이 가능하다는 것을 확인할 수 있다. 


tensor([[6., 6.],
        [3., 3.]])

In [35]:
t = torch.FloatTensor([[1,2],[3,4]])
t.mean(dim=0) #dim 0을 없애겠어라고 이해하자.
#sum 또한 비슷하다고 보자.


tensor([2., 3.])

In [36]:
t.max()

tensor(4.)

In [38]:
t.argmax()

tensor(3)

In [40]:
#view():reshape와 비스무리하다. 
t.view([-1,4]) #안의 숫자 곱이 기존 텐서 원소 곱과 같으면 문제 읎다. 위에건 2x2였지?

tensor([[1., 2., 3., 4.]])

In [41]:
t.squeeze() #알아서 엘리먼트가 한개인 디멘션은 날아간다. 

tensor([[1., 2.],
        [3., 4.]])

In [48]:
t = torch.FloatTensor([[1,2,3,4]])
ts=t.squeeze()
print(ts.ndim)
print(ts.unsqueeze(0))


1
tensor([[1., 2., 3., 4.]])


In [49]:
#unsqueeze : 내가 원하는 dimension에 1을 넣어준다. 
tc= torch.LongTensor([1,2,3,4])
print(tc.float())

tensor([1., 2., 3., 4.])


In [52]:
bt = torch.ByteTensor([True,1,0,0])

In [53]:
print(bt.long())

tensor([1, 1, 0, 0])


In [54]:
torch.cat([tc,bt],dim=0)

tensor([1, 2, 3, 4, 1, 1, 0, 0])

In [60]:
ctt=torch.cat([tc,bt],dim=0)
ctt.unsqueeze((1))#앞쪽에 디멘션상 1을 추가한다고 생각하면 양호할듯.


tensor([[1],
        [2],
        [3],
        [4],
        [1],
        [1],
        [0],
        [0]])

In [61]:
#stacking. cat보다 편리
#stack 할 텐서 사이즈가 모두 같을때..
torch.stack([tc,bt])

tensor([[1, 2, 3, 4],
        [1, 1, 0, 0]])

In [64]:
pt = torch.FloatTensor([[1,2,3,4,5,5,6,12,125,125,1,25,12,51,2]])

print(torch.ones_like(pt))
print(torch.zeros_like(pt)) #device 적으로 같은 device여야 텐서 연산이 가능하다. 

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [67]:
#다중gpu 또는 cpu와 gpu간 연산 등이 그렇다.. 
#In place Ops : 기존의 연산은 메모리에 새로 선언하나, 인플레이스는 그렇지 않다.

print(pt.mul(2.))
#이제 이 뒤에 언더바를 넣으면 메모리에 새로 선언하지 않고 결과값을 현 메모리 주소에 넣는다.
print(pt)
pt.mul_(2.)

tensor([[  2.,   4.,   6.,   8.,  10.,  10.,  12.,  24., 250., 250.,   2.,  50.,
          24., 102.,   4.]])
tensor([[  1.,   2.,   3.,   4.,   5.,   5.,   6.,  12., 125., 125.,   1.,  25.,
          12.,  51.,   2.]])


tensor([[  2.,   4.,   6.,   8.,  10.,  10.,  12.,  24., 250., 250.,   2.,  50.,
          24., 102.,   4.]])

In [68]:

print(pt)
#inplace 연산은 속도 면에서 빠르지 않을까...?
#하지만 파이토치에서 이미 가비지 컬렉터가 잘 수행되기 때문에 좋다. 


tensor([[  2.,   4.,   6.,   8.,  10.,  10.,  12.,  24., 250., 250.,   2.,  50.,
          24., 102.,   4.]])
